Repository anik0103/inventory-management-system, pull requests merged in 2025-07, with the labels that each got.

#7 Test PR
  src/App.js
  src/Components/Authentication/SignIn.js
  src/Components/Dashbord/Dashboard.js
  src/Components/Dashbord/Sidebar.js
Labels: Feature

#10 Refactor Sidebar component: replace old implementation with a new des…
  src/App.js
  src/Components/Dashbord/Dashboard.js
  src/Components/Dashbord/Sidebar.js
  src/Components/Sidebar.js
Labels: Feature

#12 Add Head component and include it in App.js
  src/App.js
  src/Components/Product/Head.js
Labels: enhancement

#22 Taslim/sidebar
  package-lock.json
  package.json
  src/Components/Sidebar.js
Labels: Feature

#28 refactor: Replace Filters component with Products in routing and create Products component
  src/App.js
  src/Components/Product/Head.js
  src/Components/Product/Products.js
Labels: Feature

#32 refactor: Implement AppLayout component and enhance Sidebar with rout…
  src/App.js
  src/Components/AppLayout.js
  src/Components/Sidebar.js
Labels: Feature

#35 feat: Add react-icons and enhance Filters and Head components with improved styling
  package-lock.json
  src/Components/Product/Filters.js
  src/Components/Product/Head.js
  src/Components/Product/Products.js
  tailwind.config.js
Labels: Feature

#39 feat: Refactor Sidebar and AppLayout for improved state management an…
  src/App.js
  src/Components/Navbar.js
  src/Components/Sidebar.js
Labels: Feature

#41 feat: Refactor layout structure by consolidating AppLayout, Sidebar, …
  src/App.js
  src/Components/AppLayout.js
  src/Components/Layout/AppLayout.js
  src/Components/Supplier/Suppliers.js
  src/Components/Supplier/SuppliersHead.js
  src/Components/SystemNavigation/MenuItems.js
  src/Components/SystemNavigation/Sidebar.js
Labels: Feature

#54 Anik/auth
  src/Components/Authentication/SignIn.js
  src/asset/fakeApiResponce/mockData.json
  src/asset/fakeApiResponce/mockdata2.json
Labels: documentation

#53 Origin/supplier table/taslim/67
  src/App.js
  src/Components/Product/ProductTable.js
  src/Components/Supplier/SplDetails.js
  src/Components/Supplier/SplProductRow.js
  src/Components/Supplier/SupplierRow.js
  src/Components/Supplier/SupplierSearch.js
  src/Components/Supplier/SupplierTable.js
  src/Components/Supplier/Suppliers.js
  src/Components/Supplier/SuppliersHead.js
  src/Components/SystemNavigation/MenuItems.js
Labels: Feature
