Repository anik0103/inventory-management-system, pull requests merged in 2025-09, with the labels that each got.

#116 feat: add Bangalore suppliers and update layout in SupplierSearch and…
  src/Components/Supplier/SplDetails.js
  src/Components/Supplier/SupplierSearch.js
  src/Components/SystemNavigation/Sidebar.js
Labels: enhancement

#119 Order details/taslim/90
  src/Components/Orders/Orderdetails.js
Labels: enhancement

#132 fix: update CustomerID format in mock data
  src/asset/fakeApiResponce/mockData.json
Labels: enhancement

#145 Add OrderFullDetails component and update routing; refactor Orders and OrderTable components for improved data handling
  src/App.js
  src/Components/Orders/Order.js
  src/Components/Orders/OrderFullDetails.js
  src/Components/Orders/OrderRow.js
  src/Components/Orders/Orderdetails.js
  src/Components/Orders/Ordertable.js
Labels: Feature

#152 Update product details and mock data: change price format and modify product names and categories
  src/Components/Product/ProductDetails.js
  src/asset/fakeApiResponce/mockData.json
Labels: bug

#153 Add padding to CustomerFilters component for better layout
  src/Components/Customer/CustomerFilters.js
Labels: enhancement
